# Generated by Django 4.1.1 on 2022-09-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
    ]
